---
- name: Install UAMS client
  hosts: uams-ubuntu-hosts
  remote_user: root

  environment:
    UAMS_ACCESS_TOKEN: "{{ UAMS_ACCESS_TOKEN  }}"
    UAMS_METADATA: "{{ UAMS_METADATA  }}"
    SWO_URL: "{{ SWO_URL }}"

  roles:
    - role: solarwinds.uamsclient
